### ISSUE TITLE
项目运行起来了，但是MongoDB数据库没有数据，请问要怎么解决？

### ISSUE THREAD

**Issue by NaN-nan8** [0x3E5/orderSYS#2]
![image](https://user-images.githubusercontent.com/103033508/161724636-cf52c71f-6301-4aa1-97de-87352010345c.png)
如果方便的话，可以给个联系方式吗？

**Comment by 0x3E5** [comment]
访问“/init”路由初始化一下信息就可以了

**Comment by NaN-nan8** [comment]
![image](https://user-images.githubusercontent.com/103033508/161753326-44c1f732-0109-4d49-97dd-7e5cbed9972d.png)
上传不了图片，请问要怎么解决
