### ISSUE TITLE
上传不了图片，请问要怎么解决

### ISSUE THREAD

**Issue by NaN-nan8** [0x3E5/orderSYS#3]
![image](https://user-images.githubusercontent.com/103033508/161762968-88c7acb3-03be-4c39-b780-615df42bfc41.png)

**Comment by 0x3E5** [comment]
企鹅4722957

**Comment by xiaoliu1999** [comment]
![image](https://user-images.githubusercontent.com/33694291/162583699-ef29d069-fa99-4478-993a-009ab9f8dd1b.png)

**Comment by xiaoliu1999** [comment]
![image](https://user-images.githubusercontent.com/33694291/162583719-ef4115f4-2b69-4795-b617-ae11736b184e.png)

**Comment by 0x3E5** [comment]
问题已经修复
